language: python
python:
  - "3.3"
  - "3.4"

env:
  - APP_VERSION=6
  - APP_VERSION=7

install:
  # install the lib
  - sudo make install
  - pip3 install -r requirements.txt
  # install phpunit and php
  - sudo apt-get install php5
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod +x phpunit.phar
  - sudo mv phpunit.phar /usr/local/bin/phpunit

before_script:
  # setup owncloud
  - cd ../
  - ocdev setup core
  - cd core/apps
  - ocdev startapp --mail test --author test --version $APP_VERSION MyApp
  - cd myapp

script:
  - phpunit tests

