language: python
python:
  - 3.2
  - 3.3
  - 3.4

env:
  - APP_VERSION=6 JINJA_FROM_PIP=0
  - APP_VERSION=6 JINJA_FROM_PIP=1
  - APP_VERSION=7 JINJA_FROM_PIP=0
  - APP_VERSION=7 JINJA_FROM_PIP=1

matrix:
  # pip jinja2 does not work on 3.2
  - exclude:
    - python: 3.2
      env: APP_VERSION=6 JINJA_FROM_PIP=1
    - python: 3.2
      env: APP_VERSION=7 JINJA_FROM_PIP=1
  # uncomment if testing and one build fail should abort whole build
  fast_finish: true

before_install:
  # if not from pip, use the repo version
  - if [[ "0" == "$JINJA_FROM_PIP" ]]; then sudo apt-get install python3-jinja2; fi

install:
  # install the lib
  - pip install setuptools
  - python setup.py install
  # install phpunit and php
  - sudo apt-get install php5
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod +x phpunit.phar
  - sudo mv phpunit.phar /usr/local/bin/phpunit

before_script:
  # setup owncloud
  - cd ../
  - ocdev setup core
  - cd core/apps
  - ocdev startapp --mail test --author test --version $APP_VERSION MyApp
  - cd myapp

script:
  - phpunit tests

